### ISSUE TITLE
midwayjs 中使用，npm start 报错

### ISSUE THREAD

**Issue by Lvison** [DG-Wangtao/egg-swagger-doc#5]
npm run build && npm start
错误信息如下：
![image](https://user-images.githubusercontent.com/18593287/57292718-2e718200-70f5-11e9-8260-b4ccdf103915.png)

![image](https://user-images.githubusercontent.com/18593287/57292777-5d87f380-70f5-11e9-8b07-fd6209466053.png)

从错误来看是 启动时扫描到了common.d.ts文件，不支持export，但不知怎么解决？？求助

**Comment by Lvison** [comment]
![image](https://user-images.githubusercontent.com/18593287/57294785-4e0ba900-70fb-11e9-87eb-17f5fbbfa3d5.png)
最终解决：在检查到.d.ts文件时跳过

**Comment by DG-Wangtao** [comment]
是的，我提交了一个pr修复了这个问题，版本号更新为 `2.2.13`。
不过我自己已经不再用这个库了，而是使用了[Cody2333/koa-swagger-decorator](https://github.com/Cody2333/koa-swagger-decorator)这个库。这个库也有我自己维护的一个版本[DG-Wangtao/koa-swagger-decorator](https://github.com/DG-Wangtao/koa-swagger-decorator)。
